### ISSUE TITLE
Get rid of `ReflectionUtils::CreateModuleFunctions`

### ISSUE THREAD

**Issue by thisismydesign** [thisismydesign/autowow#33]
Currently e.g. `include Commands::Os` created module commands by the same name (see `include ReflectionUtils::CreateModuleFunctions`). This can be unclear and problematic when names are clashing. Let's get rid of it and call functions on modules explicitly. We can then also remove `reflection_utils` as a dependency.

**Comment by gomorizsolt** [comment]
Just a test comment, sorry. :)

**Comment by gomorizsolt** [comment]
Just a test comment, sorry. :)
